version: '3'
services:

  #Bitrix
  bitrix:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bitrix
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - db:/var/lib/mysql
      - ./www:/var/www/html
      
volumes:
  db:
  #www: